---
title: "Newton's Method"
author: "Katelyn Smith"
date: '2022-06-10'
output: html_document
---

```{r setup, include=FALSE}
#Problem 1
#Use your implementation of Newton’s Method to approximate the value√2.Let your initial valuex0= 2
starting_value <- 2
#initial function 
initial_function <- function(x) {
  return(x^2 - 2)
}
#derivative of inital function
initial_function_prime <- function(y) {
  return(2*y)
}
#loop to find root at tolerance 10^-4
find_root <- function(initial_value){
  tolerance <- 1000
  while (tolerance >= 10**-4){
    new_value <- initial_value - (initial_function(initial_value) / initial_function_prime(initial_value))
    print(new_value)
    tolerance <- (initial_value - new_value)
    #print(tolerance)
    initial_value <- new_value
    #print(initial_value)
  }
  return(initial_value)
}
print ( find_root(starting_value))
```
```{r}
#Problem 2
#Create a Newton’s Method implementation to have tolerance be one of theinput values for your function.  Also, instead of erasing every step, save every iterationxnon a vector that you return at the end of your algorithm.
starting_value <- 2
#initial function 
initial_function <- function(x) {
return(x^2-2)
}
#derivative of inital function
initial_function_prime <- function(y) {
  return(2*y)
}
#loop to find root at tolerance 1
find_root <- function(initial_value){
  tolerance <- 2
  iterations <- c()
  while (tolerance >= 2){
    new_value <- initial_value - (initial_function(initial_value) / initial_function_prime(initial_value))
    print(new_value)
    tolerance <- (initial_value - new_value)
    iterations <- c(iterations, new_value)
    #print(tolerance)
    initial_value <- new_value
    #print(initial_value)
  }
  return(iterations)
}
print(find_root(inital_value))
#print(iterations)
```

```{r}
#Problem 3
#Use your new implementation of Newton’s Method with a tolerance level of10−10to approximate the real root ofx3+x−1.  Let your initial valuex0=−0.7.  Using thevector returned in your answer, calculate the errorei=|xi−r|at each step, whererrepresentsthe true value.  Also calculate the current error divided by the previous error squared i.e.eie2i−1.For reference, the true value up to the 16th decimal point is 0.6823278038280193.  Whatdo you notice about the error termsei?  What do you notice about the termseie2i−1?
#Create a Newton’s Method implementation to have tolerance be one of theinput values for your function.  Also, instead of erasing every step, save every iterationxnon a vector that you return at the end of your algorithm.
starting_value <- -0.7
#initial function 
initial_function <- function(x) {
return(x^3+x-1)
}
#derivative of inital function
initial_function_prime <- function(y) {
  return(3*y^2+1)
}
#loop to find root at tolerance 1
find_root <- function(initial_value){
  tolerance <- 10
  iterations <- c()
  while (tolerance >= 10^-10){
    new_value <- initial_value - (initial_function(initial_value) / initial_function_prime(initial_value))
    #print(new_value)
    tolerance <- abs(initial_value - new_value)
    iterations <- c(iterations, new_value)
    #print(tolerance)
    initial_value <- new_value
    #print(initial_value)
  }
  error <- c()
  #print(length(iterations))
  for (i in 1:length(iterations)) {
    e <- abs(iterations[i] - .6823278038280193)
    #print(e)
    error <- c(error, e)
    print(error)
  } 
  per <- c()
for (j in 1:(length(error)-1)) {
  p <- (error[j + 1] / (error[j])^2 )
  per <- c(per, p)
}
  return(per)}
print(find_root(starting_value))
#print(iterations)
#error
#error in percentage
```
```{r}

```



