---
title: "worksheet6v1"
output: html_document
date: '2022-06-10'
author: Allison Young
help: Jeffrey Roberts, Katelyn Smith
---

```{r}
# problem 1

starting_value <- 2
#'this is the initial function- ex: f(x) = x^3-3x+1' 
initial_function <- function(x) {
  return(x**2 - 2)
}
#'this is the first derivitive of the function f(x) listed above'
initial_function_prime <- function(x) {
  return(2*x)
}
#'this is an acting function that uses the recursion function, we know ahead of time 
#that we want the tolerance to be 10^-4
#'
find_root <- function(initial_value){
  # I do not know why tolerance is 1000 in this case
  tolerance <- 1000
  while (tolerance >= 10**-4){
    new_value <- initial_value - (initial_function(initial_value) / initial_function_prime(initial_value))
    print(new_value)
    tolerance <- (initial_value - new_value)
    #print(tolerance)
    initial_value <- new_value
    #print(initial_value)
  }
  return(initial_value)
}
print ( find_root(starting_value))

```

```{r}
# problem 2 
 # Create a Newton’s Method implementation to have tolerance be one of the input values for your function. Also, instead of erasing every step, save every iteration xn on a vector that you return at the end of your algorithm.

# input value that the tolerance will be : original starting value 

starting_value <- 2
# 'this is the initial function- ex: f(x) = x^3-3x+1' 
initial_function <- function(x) {
  return(x^2 - 2)
}
# 'this is the first derivitive of the function f(x) listed above'
initial_function_prime <- function(x) {
  return(2*x)
}
#this is an acting function that uses the recursion function, we know ahead of time 
#that we want the tolerance to be 10^-4
# the iteration step is while
find_root <- function(initial_value){
  # all tolerances need to be the same exact number for this case
  tolerance <- 2
  # line below creates an empty vector 
  e_vector <- c()
  while (tolerance >= 2 ){
    new_value <- initial_value - (initial_function(initial_value) / initial_function_prime(initial_value))
    print(new_value)
    tolerance <- (initial_value - new_value)
    # line below puts new_value in the empty spots of the e_vector which was previously empty
    e_vector <- c(e_vector , new_value)
    initial_value <- new_value
  }
  #return(initial_value)
  return(e_vector)
}
print ( find_root(initial_value))
print(e_vector)

```

```{r}

 
#Problem 3 working 

starting_value <- -0.7
#initial function 
initial_function <- function(x) {
return(x^3+x-1)
}
#derivative of inital function
initial_function_prime <- function(y) {
  return(3*y^2+1)
}
#loop to find root at tolerance 1
find_root <- function(initial_value){
  tolerance <- 10
  iterations <- c()
  while (tolerance >= 10^-10){
    new_value <- initial_value - (initial_function(initial_value) / initial_function_prime(initial_value))
    #print(new_value)
    tolerance <- abs(initial_value - new_value)
    iterations <- c(iterations, new_value)
    #print(tolerance)
    initial_value <- new_value
    #print(initial_value)
  }
  error <- c()
  #print(length(iterations))
  for (i in 1:length(iterations)) {
    e <- abs(iterations[i] - .6823278038280193)
    #print(e)
    error <- c(error, e)
    print(error)
  } 
  per <- c()
for (j in 1:(length(error)-1)) {
  p <- (error[j + 1] / (error[j])^2 )
  per <- c(per, p)
}
  return(per)}
print(find_root(starting_value))
#print(iterations)


```

```{r}

# problem 3 J working 

iterations <- c()
newtonsMethod <- function(x_0) {
  x_n = x_0 - f_input(x_0) / f_prime(x_0)
  iterations <<- c(iterations, x_n)
  
  if (abs(x_0 - x_n) < 10^(-10))
    return(x_n)
  else
    return(newtonsMethod(x_n))
}
f_input <- function(x) {
  return(x^3 + x - 1)
}
f_prime <- function(x) {
  return(3 * x^2 + 1)
}
x_i <- newtonsMethod(-7)
error_array <- c()
for (i in iterations)
  error_array <<- c(error_array, abs(i - x_i))
print(error_array)
quadratic_array <- c()
for (i in 1:(length(error_array)-1))
  quadratic_array <<- c(quadratic_array, error_array[i+1] / error_array[i]^2)
print(quadratic_array)
  
```

```{r}
# problem 4 Python to R

iterations <- c()
newtonsMethod <- function(x_0) {
  x_n = x_0 - f_input(x_0) / f_prime(x_0)
  iterations <<- c(iterations, x_n)
  
  if (abs(x_0 - x_n) < 10^(-10))
    return(x_n)
  else
    return(newtonsMethod(x_n))
  
}
f_input <- function(x) {
  return(x^2)
}
f_prime <- function(x) {
  return(2*x)
}

# in the () of newtonsMethod goes the x_0
# x_i is the approximation 
x_i <- newtonsMethod(1)
print(x_i)

error_array <- c()
for (i in iterations)
  error_array <<- c(error_array, abs(i - x_i))
print(error_array)
quadratic_array <- c()
for (i in 1:(length(error_array)-1))
  quadratic_array <<- c(quadratic_array, error_array[i+1] / error_array[i])
print(quadratic_array)

```

```{r}
# problem 5 Python to R

iterations <- c()
newtonsMethod <- function(x_0) {
  x_n = x_0 - f_input(x_0) / f_prime(x_0)
  iterations <<- c(iterations, x_n)
  
  if (abs(x_0 - x_n) < 10^(-10))
    return(x_n)
  else
    return(newtonsMethod(x_n))
  
}
f_input <- function(x) {
  return(x^2)
}
f_prime <- function(x) {
  return(2*x)
}

# in the () of newtonsMethod goes the x_0
# x_i is the approximation 
x_i <- newtonsMethod(1)
print(x_i)

error_array <- c()
for (i in iterations)
  error_array <<- c(error_array, abs(i - x_i))
print(error_array)
quadratic_array <- c()
for (i in 1:(length(error_array)-1))
  quadratic_array <<- c(quadratic_array, error_array[i+1] / error_array[i])
print(quadratic_array)


```



```{r}
#Problem 5 R to R

starting_value <- 1
#initial function 
initial_function <- function(x) {
return(x^2)
}
#derivative of inital function
initial_function_prime <- function(y) {
  return(2*y)
}
#loop to find root at tolerance 1
find_root <- function(initial_value){
  tolerance <- 10
  iterations <- c()
  while (tolerance >= 10^-10){
    new_value <- initial_value - (initial_function(initial_value) / initial_function_prime(initial_value))
    #print(new_value)
    tolerance <- abs(initial_value - new_value)
    iterations <- c(iterations, new_value)
    #print(tolerance)
    initial_value <- new_value
    #print(initial_value)
  }
  error <- c()
  #print(length(iterations))
  for (i in 1:length(iterations)) {
    e <- abs(iterations[i] - .6823278038280193)
    #print(e)
    error <- c(error, e)
    print(error)
  } 
  per <- c()
for (j in 1:(length(error)-1)) {
  p <- (error[j + 1] / (error[j]))
  per <- c(per, p)
}
  return(per)}
print(find_root(starting_value))
#print(iterations)


```


